name: 'My JS Action'
description: 'An example JavaScript action'
inputs:
  name:
    description: 'The name to greet'
    required: true
outputs:
  greeting:
    description: 'The greeting message'

runs:
  using: 'node16'
  main: 'index.js'
