name: "My Custom JS Action"
description: "A simple action to greet by name"

inputs:
  name:
    description: "The name to greet"
    required: true
    default: "World"

outputs:
  greeting:
    description: "The greeting message"

runs:
  using: "node16" 
  main: "index.js"
