name: "CI with Custom Action"

on:
  push:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Use custom JavaScript action
        id: greet  
        uses: actions/js-action@v3
        with:
          name: "Raghu"  
          
      - name: Display greeting output
        run: |
          echo "Greeting message: ${{ steps.greet.outputs.greeting }}"
