name: "CI with Custom Action"

on:
  push:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run custom action
        id: greet  
        uses: ./
        with:
          name: Raghu

      - name: Display output
        run: echo "Greeting message = ${{ steps.greet.outputs.greeting }}"
