name: "CI with Custom Action"

on:
  push:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run custom action
        id: greet  # Assign an ID to reference this step's outputs
        uses: ./my-action  # Use your local custom action
        with:
          name: "Raghu"  # Provide input for the action

      - name: Display output
        run: echo "Greeting message: ${{ steps.greet.outputs.greeting }}"
